# Generated by Django 5.2.6 on 2025-09-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Emprendimiento')),
                ('dueño', models.CharField(max_length=100, verbose_name='Nombre del Dueño')),
                ('lugar', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('productos', models.TextField(verbose_name='Productos que ofrece')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
